### PR TITLE
Hotfix for local Sonos Library Playlist. Smily Cover if not exist and…

### LINKED ISSUE #32: Playlist not loading if no picture is set
If an playlist has no logo/picture, Sonos-Kids-Controller doesn't list the playlist. Maybe an generic logo could be shown?

### LINKED ISSUE #37: add Sonos Playlist check
To add a Sonos Playlist, its requre to add an Artist. But the input Field is not editable.

### PR DESCRIPTION
**Pull request by imhofroger**
… Gui check Artist fix - fixed #32 fixed #37

### CODE REVIEW

**Comment by HeikoGr** [comment]
This fix doesn't work for me. Example playlist id: 3tNWRbrhz2sItoSr5N8My8 (yakari)
There is still no image/button for this playlist.

**Comment by imhofroger** [comment]
ohh... crap. add the Smily Cover Image only for local Sonos Playlists.

**Comment by HeikoGr** [comment]
my fault... i should learn to write propper issues.

**Comment by imhofroger** [comment]
So, thats a "problem" from Spotify. Its not a Cover defined for those Playlist. You can add your own cover Picture for your playlists.
https://support.spotify.com/us/article/add-playlist-cover/

**Comment by HeikoGr** [comment]
Yes, but only for my own playlists (as you wrote).

**Pull request closed without merging**
