### PR TITLE
Add Time to Speech Configuration

### PR DESCRIPTION
**Pull request by imhofroger**
Add Time to Speech Configuration
Now its Possible to Enable or Disable Time to Speech function. Set Language and define Volumen for Speech.
"ttsEnable": true,
"ttsLanguage": "de-de",
"ttsVolume": "60"

### CODE REVIEW

**Comment by imhofroger** [comment]
Add Time to Speech Configuration
Now its Possible to Enable or Disable Time to Speech function. Set Language and define Volumen for Speech.
"ttsEnable": true,
"ttsLanguage": "de-de",
"ttsVolume": "60"

**Comment by Thyraz** [comment]
Hey, thank you very much for this PR.

It seems like you pushed more commits on this PR that are not related to enhancing TTS.
There's also a fix for adding Spotify content by unique id as far as I can see, and also some style related stuff that shouldn't get the default (but might be a good idea that the user can configure it).

Any chance that you can split that in different PRs?

**Comment by imhofroger** [comment]
ok i will tray.. im not that stag witg git

**Comment by Thyraz** [comment]
I'm also not sure if I could simply pick the needed commits instead of merging the whole PR.
It's my first bigger project in Git too, and the first one where I get PRs...

A way on your side that might be possible: create a new branch starting on my last commit and name it something like "tts".
Then "cherry pick" single commits from your master branch to the new one.

As long as single commits didn't mix up different topics, this should be easy.
Then create a PR just for this branch instead you master branch.

Not sure if cherry picking is somewhere in the GitHub UI, I use GItKraken as a client which makes this quite easy.

If everything fails or it's too much of a hassle, just tell me and I can copy the code for the TTS fix manually.

**Pull request closed without merging**
